# Generated by Django 4.1.3 on 2022-11-14 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=255)),
                ('product_name', models.TextField()),
                ('price', models.PositiveBigIntegerField()),
                ('product_link', models.TextField()),
                ('images_link', models.TextField()),
                ('ctime', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField()),
                ('view_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authen.user')),
            ],
            options={
                'db_table': 'products_user',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ManyToManyField(through='product.ProductUser', to='authen.user'),
        ),
    ]
