# Generated by Django 4.1.3 on 2022-11-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productuser',
            name='favorite',
            field=models.BooleanField(null=True),
        ),
    ]
